### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mrtnzlml** [rostaklein/kiwi-task#1]
Hi Rosťa 👋. I tried to run this project (`yarn && yarn dev`) but it throws an exception when I press the key on your nice keybord:

```
Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Suggestions (http://localhost:3000/_next/-/page/index.js:510:31)
    at ProxyComponent.proxiedRender (http://localhost:3000/_next/-/main.js:28011:16)
    at finishClassComponent (http://localhost:3000/_next/-/main.js:19200:33)
    at updateClassComponent (http://localhost:3000/_next/-/main.js:19168:12)
    at beginWork (http://localhost:3000/_next/-/main.js:19793:16)
    at performUnitOfWork (http://localhost:3000/_next/-/main.js:22625:16)
    at workLoop (http://localhost:3000/_next/-/main.js:22654:26)
    at renderRoot (http://localhost:3000/_next/-/main.js:22685:9)
    at performWorkOnRoot (http://localhost:3000/_next/-/main.js:23260:24)
    at performWork (http://localhost:3000/_next/-/main.js:23181:9)
```

Can you please fix it and let me know? This is quite important since we cannot accept not working solution.

One other thing. I didn't see a single test file. Please add at least super simple unit tests so we can see that you actually know how to write them. Thank you very much.

**Comment by rostaklein** [comment]
Hello Martin, I am really sorry, i could have added some readme. You need
to run the API separately (its a separate "subproject"). The command is *npm
api* (or *yarn api*).

I thought the test are not a requirement, but i already wrote some so ill
try to add few asap.

Thank you and have a nice day :)

**Comment by mrtnzlml** [comment]
> I could have added some readme. You need to run the API separately...

I see. Thanks for the fix. README file is very important since every project is very different. Next time please also include how to install it. I thought it's going to be enough to install it from the root but you have to run `yarn install` even from `app/` subfolder. Not so obvious... 🙂

**Comment by rostaklein** [comment]
Thanks for the comments, Martin. I updated the readme once again :) It might have been much better to separate these two as standalone projects, but i wanted to have them in one repository.

Please check the simple test i added in https://github.com/rostaklein/kiwi-task/commit/ec4ab7f5200a45b5111031299c69a41921a958cb.

Thank you.
